from brian2 import *
from watts_strogatz import watts_strogatz
from small_world_index import small_world_index
import numpy as np
import matplotlib.pyplot as plt
from izhikevich_constants import *

# Measure Small World Index on probabilistic networks generated by
# Watts Strogatz.

# Small network of 100 neurons
n = 100
swi = []

start_exp = -3
start = 10 ** start_exp
end_exp = 0
end = 10 ** end_exp

num = 100
for p in np.logspace(start_exp, end_exp, num):
    (_, _, cij) = watts_strogatz(100, 4, p, EXCITATORY_NEURON_EQS, THRES_EQ, EXCITATORY_RESET_EQ)
    swi.append(small_world_index(cij))
    print(p, swi[-1])

plt.plot(np.logspace(start_exp, end_exp, num), swi, '.b')
plt.xscale('log')
plt.show()





